# Generated by Django 5.1.7 on 2025-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_item', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('base_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'stockitems',
                'managed': False,
            },
        ),
    ]
