# Generated by Django 5.1.7 on 2025-03-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallydata', '0002_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_centre', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cost_centre',
                'managed': False,
            },
        ),
    ]
