# Generated by Django 5.1.7 on 2025-03-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallydata', '0003_costcentre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyDataAccountMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ledger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('address_3', models.CharField(blank=True, max_length=100, null=True)),
                ('address_4', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('party_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('primary_group', models.CharField(blank=True, max_length=100, null=True)),
                ('favouring_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('performance', models.CharField(blank=True, max_length=100, null=True)),
                ('representative', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tallydata_accountmaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TallyDataCostCentre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tallydata_costcentre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TallyDataInventoryMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_item', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('base_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tallydata_inventorymaster',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CostCentre',
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.DeleteModel(
            name='StockItems',
        ),
    ]
