# Generated by Django 5.1.7 on 2025-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallydata', '0005_tallydatasales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyDataReceviables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('ledger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('representative', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tallydata_receviables',
                'managed': False,
            },
        ),
    ]
