# Generated by Django 5.1.7 on 2025-03-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallydata', '0006_tallydatareceviables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyDataReceivables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('ledger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('representative', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tallydata_receivables',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TallyDataReceviables',
        ),
    ]
