# Generated by Django 5.1.7 on 2025-03-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallydata', '0007_tallydatareceivables_delete_tallydatareceviables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyDataPurchases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('ledger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('broker', models.CharField(blank=True, max_length=100, null=True)),
                ('item_count', models.FloatField(blank=True, null=True)),
                ('item_no', models.FloatField(blank=True, null=True)),
                ('stock_item', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('packing', models.FloatField(blank=True, null=True)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('cartage', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tallydata_purchases',
                'managed': False,
            },
        ),
    ]
